FROM golang:1.14.6-alpine3.12 as build

RUN apk add --no-cache git

WORKDIR /src 

RUN go get github.com/sirupsen/logrus
RUN go get github.com/streadway/amqp

COPY consumer.go /src 

RUN go build consumer.go


FROM alpine:3.12 as runtime

COPY --from=build /src/consumer /app/consumer

CMD [ "/app/consumer" ]