apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      orgId: 1
      type: prometheus 
      url: http://prometheus-service:9090
      isDefault: true
      access: proxy
      editable: true