FROM ubuntu

RUN apt-get update
RUN apt-get install sudo -y

RUN apt-get update
RUN apt-get install software-properties-common -y

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key 8CF63AD3F06FC659
RUN add-apt-repository ppa:jonathonf/vim -y

RUN apt-get update
RUN apt-get install vim -y

RUN apt-get install curl -y

RUN useradd -u 1000 -m rh

RUN usermod -aG sudo rh

RUN echo "%sudo  ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY .vimrc /home/rh/
COPY .vim /home/rh/.vim/
RUN chown rh:rh /home/rh/.vimrc
RUN chown -R rh:rh /home/rh/.vim/

USER rh

WORKDIR /home/rh

ENTRYPOINT [ "/bin/bash" ]